export const EMAILJS_CONFIG = {
  SERVICE_ID: import.meta.env.PUBLIC_EMAILJS_SERVICE_ID,
  TEMPLATE_ID: import.meta.env.PUBLIC_EMAILJS_TEMPLATE_ID,
  PUBLIC_KEY: import.meta.env.PUBLIC_EMAILJS_PUBLIC_KEY,
}; 